name: Docker Image CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v2
      
    - name: 设置jdk1.8.0
      uses: actions/setup-java@v1
      with:
        java-version: 1.8.0
        
    - name: Maven编辑打包跳过测试
      run: mvn package -DskipTests
      
    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v1
  
    - name: Login in docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: housihai/myspringboot:0.0.1
